### ISSUE TITLE
certain dada dependencies within package not found by max

### ISSUE THREAD

**Issue by michaelpalumbo** [bachfamily/dada#1]
Hi there! I'm really excited to experiment with this lib -- cage and bach were both pretty cool :D

However, many of the externals required by the package are not being found by max in the ~/packages/* search path, such as 'dada.kaleido'

tested on Max8 and Max 7.

**Comment by danieleghisi** [comment]
Hi Michael,

the actual Package folder is not the one you mention (AFAIK), but
~/Documents/Max #/Packages/

if you put the dada folder over there, you should be able to work with
it. If you don't need to compile the code or modify it, you should
simply download the release from http://www.bachproject.net/dl/ and
put it in the Packages folder.

Hope this helps,
Daniele

Il giorno ven 8 feb 2019 alle ore 20:54 Michael Palumbo
<notifications@github.com> ha scritto:

**Comment by michaelpalumbo** [comment]
Thanks Daniele,

So I put the release folder in the packages directory (where cage and bach and others are already installed.) The dada.overview patch in the extras folder loads, and “newobbj bach.join: no such object” prints three times in the max console. Further, when I try to open any of the help patchers (either through the overview patch or directly clicking the file) max crashes. This is repeatable on max 8 and max 7.

Not sure what do try next.

Best regards,

Michael

**Comment by danieleghisi** [comment]
You need at least bach 0.8 to run dada, as the websitw explains. It seems
to me that you have mismatching versions.
I suggest to delete bach and cage and redownload them from the website
download page (not from the package manager, where there's still 0.7.9).

Let me know,
D

Il giorno dom 10 feb 2019, 22:07 Michael Palumbo <notifications@github.com>
ha scritto:

**Comment by michaelpalumbo** [comment]
ah yes! That fixed it, and can verify it works on both max 7 and max 8. Thanks for your help on this! The package looks fantastic.

Best,

Michael

---------

Michael Palumbo
PhD Student, Theatre & Performance Studies
York University, Toronto

647-290-1552
info@palumbomichael.com
http://michaelpalumbo.github.io
http://dispersionlab.org/people/michael-palumbo/
